"""Create version and type

Revision ID: 2ac22256ac88
Revises: 57b7bb118142
Create Date: 2025-04-28 10:02:00.779100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac22256ac88'
down_revision: Union[str, None] = '57b7bb118142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('licence_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('questions_licence_types_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'licence_types', ['licence_type_id'], ['id'])
    op.drop_column('questions', 'licence_types_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('licence_types_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_licence_types_id_fkey', 'questions', 'licence_types', ['licence_types_id'], ['id'])
    op.drop_column('questions', 'licence_type_id')
    # ### end Alembic commands ###
