"""Create version and type

Revision ID: 57b7bb118142
Revises: e3c5dc42168f
Create Date: 2025-04-28 09:18:34.041424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b7bb118142'
down_revision: Union[str, None] = 'e3c5dc42168f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licence_types', 'enable')
    op.add_column('versions', sa.Column('enable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versions', 'enable')
    op.add_column('licence_types', sa.Column('enable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
