"""Create licence_types, questions and choices tables

Revision ID: 8ade8dd6ce95
Revises: 
Create Date: 2025-04-28 09:02:32.697001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ade8dd6ce95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choices', sa.Column('image', sa.String(), nullable=True))
    op.add_column('licence_types', sa.Column('name', sa.String(), nullable=True))
    op.add_column('licence_types', sa.Column('enable', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_licence_types_name'), 'licence_types', ['name'], unique=False)
    op.add_column('questions', sa.Column('image', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('licence_types_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'licence_types', ['licence_types_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'licence_types_id')
    op.drop_column('questions', 'image')
    op.drop_index(op.f('ix_licence_types_name'), table_name='licence_types')
    op.drop_column('licence_types', 'enable')
    op.drop_column('licence_types', 'name')
    op.drop_column('choices', 'image')
    # ### end Alembic commands ###
