"""initial migration

Revision ID: a9729143bb50
Revises: 
Create Date: 2025-04-29 12:49:40.727580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9729143bb50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licence_types', sa.Column('description', sa.String(), nullable=True))
    op.add_column('licence_types', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licence_types', 'image')
    op.drop_column('licence_types', 'description')
    # ### end Alembic commands ###
