"""Create version and type

Revision ID: e3c5dc42168f
Revises: 8ade8dd6ce95
Create Date: 2025-04-28 09:17:37.293877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c5dc42168f'
down_revision: Union[str, None] = '8ade8dd6ce95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_id'), 'types', ['id'], unique=False)
    op.create_index(op.f('ix_types_name'), 'types', ['name'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_id'), 'versions', ['id'], unique=False)
    op.create_index(op.f('ix_versions_year'), 'versions', ['year'], unique=False)
    op.add_column('licence_types', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('licence_types', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'licence_types', 'types', ['type_id'], ['id'])
    op.create_foreign_key(None, 'licence_types', 'versions', ['version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'licence_types', type_='foreignkey')
    op.drop_constraint(None, 'licence_types', type_='foreignkey')
    op.drop_column('licence_types', 'version_id')
    op.drop_column('licence_types', 'type_id')
    op.drop_index(op.f('ix_versions_year'), table_name='versions')
    op.drop_index(op.f('ix_versions_id'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_types_name'), table_name='types')
    op.drop_index(op.f('ix_types_id'), table_name='types')
    op.drop_table('types')
    # ### end Alembic commands ###
