"""Create version and type

Revision ID: e476b045c5d8
Revises: f9867d80660f
Create Date: 2025-04-28 11:05:44.197491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e476b045c5d8'
down_revision: Union[str, None] = 'f9867d80660f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_type_id', table_name='question_type')
    op.drop_index('ix_question_type_name', table_name='question_type')
    op.drop_table('question_type')
    op.drop_index('ix_question_types_id', table_name='question_types')
    op.drop_index('ix_question_types_name', table_name='question_types')
    op.drop_table('question_types')
    op.add_column('questions', sa.Column('question_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'questions_type', ['question_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'question_type_id')
    op.create_table('question_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='question_types_pkey')
    )
    op.create_index('ix_question_types_name', 'question_types', ['name'], unique=False)
    op.create_index('ix_question_types_id', 'question_types', ['id'], unique=False)
    op.create_table('question_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='question_type_pkey')
    )
    op.create_index('ix_question_type_name', 'question_type', ['name'], unique=False)
    op.create_index('ix_question_type_id', 'question_type', ['id'], unique=False)
    # ### end Alembic commands ###
