"""Create version and type

Revision ID: f9867d80660f
Revises: 2ac22256ac88
Create Date: 2025-04-28 10:50:39.707752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9867d80660f'
down_revision: Union[str, None] = '2ac22256ac88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('num', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_questions_num'), 'questions', ['num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_num'), table_name='questions')
    op.drop_column('questions', 'num')
    # ### end Alembic commands ###
